### ISSUE TITLE
MSBUILD : error MSB1009: Project file does not exist.     Switch: VCTargetsPath.vcxproj

### ISSUE THREAD

**Issue by BurhanMohayeddin** [CoppeliaRobotics/simExtOMPL#7]
Hi, I want to install OMPL plugin for vrep. Based on guidelines I have successfully done these lines of codes:
$ git clone --recursive https://github.com/CoppeliaRobotics/v_repExtOMPL.git
$ cd v_repExtOMPL
However, when I run this line:
$ cmake .
It gave me that error. I have attached the log file and the screenshot of the error. Please, can you help me? Thank you very much. By the way, I use VS2017(Version 15.9).
[CMakeOutput.log](https://github.com/CoppeliaRobotics/v_repExtOMPL/files/3172175/CMakeOutput.log)
![Capture](https://user-images.githubusercontent.com/36763498/57611450-f8fce680-7583-11e9-9595-30b66972b547.PNG)

**Comment by aidyk** [comment]
A related question can be found here: [link to stackoverflow](https://stackoverflow.com/questions/44478492/cmake-failed-to-run-msbuild-command-msbuild-exe)
If you have the MSBuild.exe in the right location, try dedicated prompts e.g., Visual Studio Command Prompt for running cmake.
